### ISSUE TITLE
msg_id too low

### ISSUE THREAD

**Issue by androidacy-user** [ashwinstr/UX-itachi#79]
Pyrogram crashes, insisting time needs synced, however:

```bash
$ timedatectl status
               Local time: Tue 2023-06-20 13:30:42 EDT
           Universal time: Tue 2023-06-20 17:30:42 UTC
                 RTC time: Tue 2023-06-20 17:30:42
                Time zone: US/Eastern (EDT, -0400)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

Full stack:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/userbot/userge-x/userge/__main__.py", line 14, in <module>
    userge.begin()
  File "/home/userbot/userge-x/userge/core/client.py", line 201, in begin
    self.loop.run_until_complete(self.start())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/userbot/userge-x/userge/core/client.py", line 155, in start
    await super().start()
  File "/home/userbot/userge-x/venv/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 52, in start
    is_authorized = await self.connect()
  File "/home/userbot/userge-x/venv/lib/python3.9/site-packages/pyrogram/methods/auth/connect.py", line 46, in connect
    await self.session.start()
  File "/home/userbot/userge-x/venv/lib/python3.9/site-packages/pyrogram/session/session.py", line 142, in start
    raise e
  File "/home/userbot/userge-x/venv/lib/python3.9/site-packages/pyrogram/session/session.py", line 109, in start
    await self._send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT)
  File "/home/userbot/userge-x/venv/lib/python3.9/site-packages/pyrogram/session/session.py", line 334, in _send
    raise BadMsgNotification(result.error_code)
pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.
```

**Comment by anonymousx97** [comment]
It's due to old pyrogram version
afaik only DC1 accounts are affected by this for now.
and no there's nothing can be done unless someone ports old code to pyrogram v2

**Comment by billouetaudrey** [comment]
The solution is to use Pyro 2.x but UX is not compatible with Pyro 2.x

**Comment by billouetaudrey** [comment]
@billouetaudrey https://github.com/pyrogram/pyrogram/issues/101

**Comment by androidacy-user** [comment]
> The solution is to use Pyro 2.x but UX is not compatible with Pyro 2.x

any alternatives? venomX doesn't work because it has something depending on `futures` which won't install on python3.10 but another dep requires it

**Comment by anonymousx97** [comment]
@androidacy-user
pip install -U setuptools wheel
will fix the futures issue

**Comment by billouetaudrey** [comment]
@anonymousx97 No fix for UX 😢

**Comment by androidacy-user** [comment]
> @androidacy-user pip install -U setuptools wheel will fix the futures issue

no dice

```python
[20-Jun-23 14:08:50 - INFO] - venom.core.ext.pool - <<<   ||| Started Pool : 80 Workers |||   >>>
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/userbot/VenomX/venom/__main__.py", line 16, in <module>
    venom.run()
  File "/home/userbot/VenomX/venv/lib/python3.10/site-packages/pyrogram/methods/utilities/run.py", line 80, in run
    run(self.start())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/userbot/VenomX/venom/core/client.py", line 161, in start
    await self.start_client()
  File "/home/userbot/VenomX/venom/core/client.py", line 72, in start_client
    r: BotResults = await self.get_inline_bot_results("VenomX_authenticator_bot", query="get_users_list")
  File "/home/userbot/VenomX/venv/lib/python3.10/site-packages/pyrogram/methods/bots/get_inline_bot_results.py", line 75, in get_inline_bot_results
    return await self.invoke(
  File "/home/userbot/VenomX/venv/lib/python3.10/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
  File "/home/userbot/VenomX/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
  File "/home/userbot/VenomX/venv/lib/python3.10/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/userbot/VenomX/venv/lib/python3.10/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.BotResponseTimeout: Telegram says: [400 BOT_RESPONSE_TIMEOUT] - The bot did not answer to the callback query in time (caused by "messages.GetInlineBotResults")
```

**Comment by anonymousx97** [comment]
@androidacy-user
try this repo for now https://github.com/VenomXuserbot/VenomX
the repo you are using is beta and is highly unstable.

**Comment by androidacy-user** [comment]
> @androidacy-user try this repo for now https://github.com/VenomXuserbot/VenomX the repo you are using is beta and is highly unstable.

```python
[20-Jun-23 15:32:31 - INFO] - venom.core.client - ### Starting bot ###
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/userbot/VenomX/venom/__main__.py", line 7, in <module>
    venom.run()
  File "/home/userbot/VenomX/venv/lib/python3.10/site-packages/pyrogram/methods/utilities/run.py", line 80, in run
    run(self.start())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/userbot/VenomX/venom/core/client.py", line 134, in start
    await self.bot.start()
  File "/home/userbot/VenomX/venv/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 73, in start
    await self.initialize()
  File "/home/userbot/VenomX/venv/lib/python3.10/site-packages/pyrogram/methods/auth/initialize.py", line 45, in initialize
    self.load_plugins()
  File "/home/userbot/VenomX/venv/lib/python3.10/site-packages/pyrogram/client.py", line 634, in load_plugins
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/userbot/VenomX/venom/plugins/test/test.py", line 3, in <module>
    import pyromod.filters
ModuleNotFoundError: No module named 'pyromod.filters'
```

**Comment by fnixdev** [comment]
@androidacy-user

**Comment by anonymousx97** [comment]
Try now, it should be fixed on both repos

**Comment by androidacy-user** [comment]
> Try now, it should be fixed on both repos 

```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/userbot/VenomX/venom/__init__.py", line 7, in <module>
    from .config import Config, SecureConfig, get_devs
  File "/home/userbot/VenomX/venom/config.py", line 9, in <module>
    from pyrogram.raw.base import ForumTopic
ImportError: cannot import name 'ForumTopic' from 'pyrogram.raw.base' (/home/userbot/VenomX/venv/lib/python3.10/site-packages/pyrogram/raw/base/__init__.py)
```

**Comment by anonymousx97** [comment]
https://t.me/UX_xplugin_support
join
